<i18n>
{
  "tr": {
    "title": "Şeffaf Plaklarla Ortodonti",
    "description": "Şeffaf Plak ile Ortodontik Tedavi; şeffaf plaklar, yaklaşık geçmişi 20 yıla dayanan güvenilir bir tedavi yöntemidir. Şeffaf plaklar dışarıdan bakıldığında fark edilemezler.",
    "content1": "<p>Şeffaf Plak ile Ortodontik Tedavi; şeffaf plaklar, yaklaşık geçmişi 20 yıla dayanan güvenilir bir tedavi yöntemidir. Şeffaf plaklar dışarıdan bakıldığında fark edilemezler. En yakınlarınız bile (arkadaşlarınız, aileniz ) fark etmekte zorlanacaklardır. İstenildiği zaman takıp çıkarma imkanı bulunmaktadır. Ağrısız tedavi yöntemidir. Metal tellerinde sıkça karşılaşılan ağrı, sızı ve acı hisleri ile kesinlikle karşılaşılmaz.</p><p>Şeffaf Plaklarla metal veya şeffaf diş teli gibi estetiksel bir kaygı yaşanmaz. Aile, iş ve sosyal yaşantınıza hiçbir kaygı duymadan devam edebilirsiniz. Özellikle çocukların ve gençlerin diş çarpıklığı tedavilerinde yaşadıkları psikolojik sorunların önüne geçmektedir.</p><p>Dişlerin üzerini kaplayan plak tabakası sayesinde ağızda ortodontik müdahaleler yapılır. Şeffaf plaklar kolayca çıkarılıp takılabilen, yumuşak yapısıyla kullanımı kolay bir tedavi aygıtı olup tamamen şeffaf yapısıyla da oldukça estetik bir tedavi aracıdır.</p>",
    "accord1title": "Şeffaf Plaklar Nasıl Hazırlanır?",
    "accord1": "<p>Diş hekimi ağızdan ölçü alır. Bu bilgileri üç boyutlu tarama yöntemi ile bilgisayara aktarır. Bilgisayar üzerinde dişlerin hareketine dair tedavi plan senaryosu elde edilir. Bu senaryolara göre tedavi rotası belirlenir. Üç boyutlu yazıcıdan istenen diş kalıpları çıkarılır. Elde edilen bu kalıpların üzerine esnek şeffaf plak uygulanır. Tedavi aşamalarında kat edilecek yol için her bir adıma uygun plak hazırlanır. Böylece tedavide kullanılacak plaklar hazırlanmış olur.</p>",
    "accord2title": "Plaklar Nasıl Kullanılır?",
    "accord2": "<p>Şeffaf plaklar dişlerin üzerine oturtulur, dişleri kaplayarak ağızda bulundukları sürece dişleri istenen yöne doğru hareket ettirirler. Plağın kullanımı sadece ağıza yerleştirilmesi, yeme, içme, diş fırçalama, diş ipi kullanma gibi aktivitelerde çıkarma şeklindedir. Yani kişi plağını kendisi çıkartıp takabilir. Plağı bizzat kendisi günlük hayatının bir parçası olarak kullanır.</p>",
    "accord3title": "Ölçüler Alındıktan Sonra Tedavi Ne Zaman Başlar?",
    "accord3": "<p>Ölçüler alındıktan sonra bilgilerin bilgisayara girilmesi ve kalıpların hazırlanma sürelerini göz önünde bulundurursak şeffaf plaklar yaklaşık iki hafta sonra elde edilir. Yani plaklar iki hafta sonra alınıp ağıza yerleştirilir ve tedaviye başlanmış olunur.</p>",
    "accord4title": "Şeffaf Plaklar ile Tedavi Süreci Nasıl İlerler?",
    "accord4": "<p>Şeffaf plaklarda normal ortodontik tedaviden farklı olarak braketler kişinin kendisine özel olarak 3 boyutlu yazıcılar tarafından üretilir. Plaklar ağızda bulundukları sürece dişleri istenen harekete doğru yönlendirir. 15 günde bir plak değiştirilir ve her değişimde, yani her yeni plakta dişler istenen yöne doğru planlı bir şekilde ilerletilir.</p><p>Tedavi süresince hastalar plakları çok rahat bir şekilde kendileri takip çıkarabilirler, oldukça basittir, bir plağı günde yaklaşık 20 saat kullanırlar, plağı kullandıktan yaklaşık iki hafta sonra bir sonraki adımın plağı kullanılmak üzere verilir. Bu plağı yine aynı şekilde iki hafta boyunca günde 20 saat gibi bir süre ile takarak kullanırlar.</p>",
    "accord5title": "Şeffaf Plak Kullanımında Tedavi Süresi Nedir?",
    "accord5": "<p>Ortalama tedavi süresi, problemlerin yaklaşık %60’ı sekiz ila on ayda biter. Kalan %40 ise on iki ila on dört aylık tedavilerle sonlanabilir. Maksimum 16-18 ay süren ender durumlar da vardır.</p>",
    "accord6title": "Şeffaf Plak Kullanımının Sabit Braketlere Göre Avantajları Nelerdir?",
    "accord6": "<p>Plağın diş tellerine göre avantajları çok fazladır. Yapılan bütün hareketler üç boyutlu simülasyonlarda öncelikle belirlenir. Ondan sonrasında istenmeyen bir hareket oluşma miktarı oldukça düşüktür, riski pek yoktur, yapılan çalışmalarda tellere göre dişlere daha az zarar veriyor ya da daha çok zarar veriyor diye bir bulguya rastlanmamıştır, diş tellerinden bu noktada farkı yoktur.</p><p>Oldukça şeffaftırlar, estetik bir görünümleri vardır, dışardan bakılınca kullanıcının tedavisinin sürüp sürmediği, tedavi olunduğu yada tedavinin hangi sürecinde olunduğu anlaşılamaz.</p><p>Hastanın kendine özgü birebir üretildiği için problem yaşanmaz. Sosyal yaşantıyı sekteye uğratmaz, şeffaf plak kullanan biri toplum içindeki gülme konuşma gibi doğal davranışlarını rahatlıkla sürdürebilir. Konuşurken ağzını eliyle kapatmaz. Resim çekilirken telleri gözükmesin diye gülmemezlik yapmaz, hayatin doğal akışında rahatlıkla yaşama devam eder, bir tedavi süreci içindedir ama yaşam kalitesi düşmez.</p><p>Yemeklerde çıkarılabildiği için rahatlıkla istenen her şey yenebilir, tellere göre en büyük avantajlarından biri budur. Diğer büyük avantajı temizlik çok daha kolaydır. Tellerde dişlere giren besinleri temizlemek zorken şeffaf plaklar çıkarılabildiğinden, kullanıcı rahatlıkla tüm dişlerini temizleyebilir. Estetik görünümüyle sosyal yaşantıyı etkilememesi ve çıkarılabilmesiyle istenen yiyeceklerin tüketilip diş hijyeninin rahatlıkla sağlanabilmesi plak kullanımının en büyük avantajlarıdır. Tedavi sürecinde kliniğe gelindiğinde plak değişimleri kısa sürede yapılır, metal braketlerdeki gibi tel ayarı, sıkılaştırılması, değişimi gibi tedavi uygulamaları olmayacağı için klinikte geçen süre tellere göre oldukça azdır.</p><p>Seyahat sırasında sürdürebilen bir süreç şeffaf plak tedavisi.</p><p>Eğer tedavi elveriyorsa hastaya birkaç plak verilip süreç kendisinin eline verilebilir, kliniğe geliş süresi azalır, tedavi uygunsa plakları hasta arka arkaya kullanabilir.</p><p>Şeffaf plaklar bilgisayar teknolojisi ile üretildikleri için istenmeyen bölgelere gereksiz kuvvet uygulamaz, istenen bölgelere gerektiği kadar kuvvet uygularlar.</p>",
    "accord7title": "Şeffaf Plak Kullanımının Dezavantajları Nelerdir?",
    "accord7": "<p>Şeffaf plak kullanıcıları plağı ilk taktıklarında tükürük salgısında bir miktar artış olabiliyor, alışma sürecinde peltek konuşma görülebiliyor.</p><p>Fiyat olarak sabit braketlere göre daha maliyetli olmasını da bir olumsuzluk olarak sayabiliriz.</p>",
    "accord8title": "Şeffaf Plak Kullanımı ile Diş Teli Kullanımı Arasındaki Farklar Nelerdir?",
    "accord8": "<p>Metal braketlerde telin koptuğu, çıktığı durumlar olur. Bu durumlarda kliniğe gidilir, diş hekimi teli yerine yerleştirir. Bu gibi olası senaryolarda klinik ziyaretleri şart olur. Şeffaf plak kullanıcısı diş hekimine bağlı değil daha bağımsız bir tedavi süreci geçirir. Seyahat edebilir, hasta yada yoğun olduğunda kliniğe gelmesi zaruri durumlar yaşamadığı için ajandasına sadece kontrol randevularını yazmalıdır, bunun dışında ekstra klinik ziyareti yaşamak durumunda kalmaz.</p><p>Yine tedavinin estetik yapısından dolayı Plak kullanıcıları tedavinin ne zaman biteceğine dair ilgili değildirler. Metal braket kullanan hastaların hemen hemen her muayenede sorduğu soru tellerin ne zaman çıkacağıdır, oysa invisalign teknolojisinde hastalar tedavi süresini dert etmez.</p><p>Diğer bir dezavantaj teller kırıldığında diş etini yara yapabiliyor, ağızda bulunan metal aygıtlar yada teller nedeniyle batma veya yara olma durumu söz konusu, çoğunlukla hekim müdahalesi gerekiyor, plaklarda böyle durumlar görülmüyor, müdahale edilmesi gereken durum çok nadir olur, diş ve dişetini rahatsız etmez. Braketlerle uygulanan tedaviye göre, daha konforlu daha rahat kullanım ve yarasız acısız bir tedavi süreci sunar.Metal braketlerle tedaviye göre daha acısız ve ağrısız bir süreçtir.</p>",
    "accord9title": "Şeffaf Plak Kullanmak İçin Yaş Sınırı Var Mı?",
    "accord9": "<p>Her yaş grubunda rahatlıkla kullanılabilir. İnvisalign kullanımında yaş sınırı yoktur. Çocuklar, gençler ve yetişkinler şeffaf plak kullanabilir. Önemli olan hekim ile işbirliği içinde düzenli olarak plağın kullanılmasıdır.</p>",
    "accord10title": "Şeffaf Plak Kullanırken Nelere Dikkat Edilmeli?",
    "accord10": "<p>Şeffaf plak kullanılırken hekimle işbirliği içinde olunmalı, plak düzenli bir şekilde kullanılarak ağızda bulundurulmalıdır. Plağın esnek yapısı gereği aşırı sıcak içecek tüketilmemelidir. Plak ısıdan dolayı esneyerek formunu kaybedebilir.</p>",
    "accord11title": "Plak Kullanılırken Sigara İçilebilir mi?",
    "accord11": "<p>Aşırı çay, kahve, sigara tüketimi plaklarda sararma yapabilir. Fakat plaklar 15 gün sonra değiştirildiği için renginin düzeltilmesi gibi bir çaba gerekmez. Oysa sabit ortodontik tedavide ücret vererek seanslarda dişlerinizi temizlenmesinin gerektiği durumlar olabilir.</p>",
    "accord12title": "İnvisalign Tedavisi Öncesinde Genel Diş Muayenesi Yaptırmak Gerekir mi?",
    "accord12": "<p>Tedaviye başlamadan önce diş muayenesi olup dişlerde gereken dolgu işleminin, diş taşı temizliğinin, çürüklerin temizlenmiş olması, ağız bakımının yapılmış olması gerekir. Tedaviye başlandıktan sonra bu gibi işlemler yapılmaz. Ancak implant gibi protetik işlemler tedavi sonrasına bırakılır.</p><p>Ortognatik cerrahi operasyonu öncesinde de şeffaf plak tedavisi uygulanabilir ve operasyon sonrası ağızdaki problemler giderilmiş olur.</p>",
    "accord13title": "İnvisalign, Sabit Braketlere Göre Daha Maliyetli Bir Tedavi Mi?",
    "accord13": "<p>Önceden İnvisalign daha maliyetli bir tedavi yöntemiydi. Sadece bir firma bu işi yapıyordu, daha pahalı idi, bugün fiyatlar daha uygun, ulaşılabilir düzeyde bir maliyeti var. Yine de tellere göre daha maliyetli ama arada uçurum yok.</p><p>Burada maliyet hesabı yapılırken avantaj dezavantaj kıyaslaması işin içine katılmalı. İnvisalign bir miktar daha maliyetli ama çok daha estetik ve çok daha kolay kullanımlı.</p>",
    "accord14title": "Diş Teli Tedavilerine Kıyasla Şeffaf Plakları Önerir misiniz?",
    "accord14": "<p>Ortodontik tedavi müdahalelerimi ben %80 şeffaf plaklarla yapıyorum, hastalardan talep görüyor ve hastalarım memnun, benim öncelikle tercihim bu oluyor, dijital teknolojiler hızlıca diş hekimliğine entegre olmuş durumda, bundan uzak kalmanın anlamı yok, üç boyutlu kusursuz analizler yapılıyor , bunu uygulamayı gerekli ve faydalı görüyorum.</p><p>Hastaların kendilerinin tellerle kıyaslamaları söz konusu değil haliyle, bizim klinikte gözlemlediğimiz Plak kullanıcıları tedavileri olurken çevrelerindeki insanların tedavinin farkında olmadıklarını görüyoruz. İki haftada bir plak değiştiği için herhangi bir koku, rahatsız edecek herhangi bir yönü yok.</p><p>Estetik ve hijyenik bir şekilde kolay kullanımlı bu tedaviyi sürdürebiliyorlar. Çok önemli görüşmelerinde plakları çıkarabiliyorlar, günde birkaç saat çıkarma haklarını özel durumlarda kullanabiliyorlar.</p><p>Ortodontik tedavi gören kişilerin tedavi sonuna kadar resimlerinde, sosyal medya hesaplarında gülmediklerini görüyoruz, şeffaf plak kullanıcılarının görsel anlamda endişeleri olmuyor, rahatlıkla gülüp konuşabiliyorlar, fotoğraflarda rahat davranabiliyorlar. Bu yönüyle de sosyal yaşantıyı kesintiye uğratmayan bir tedavi yöntemi. Kayıtlara göre dünya üzerinde on milyon insan şeffaf plaklarla tedavi almış ve sonuçlar çok olumlu.</p><p>Şeffaf plaklar dişleri ideal pozisyona taşıyan kolay, estetik ve sağlıklı bir metod. Bu yüzden bende genel olarak tedavi uygulamalarımda şeffaf plakları kullanıyorum.</p>",
    "accord14title": "Şeffaf Plakların Avantajları",
    "accord14": "<p>Hekim koltuğunda geçen süre daha azdır. Geleneksel diş telleri kullandığınızda hekiminize iki haftada bir gibi sıklıkla bazı ayarlar için uğramak zorundasınızdır. Şeffaf düzelticiler kullandığınızda ise hekiminize altı haftada bir uğrarsınız ve size kullanacağınız diğer bir set düzeltici plak verir.</p><p>Ağız hijyeni daha iyi olur. Geleneksel diş tellerinin aksine şeffaf düzelticilerinizi yemek yerken, içerken veya dişlerinizi fırçalarken çıkartabilirsiniz.</p><h4>Tedavi Süreci</h4><p><ul><li>Bilgisayarlı tomografi ile dişlerinizin görüntüsü alınır</li><li>Bilgisayar destekli tasarım yazılımıyla dişlerinizin hareketleri tahmin edilir</li><li>Eğer gerekliyse tedavi planınız gözden geçirilir</li><li>Tedavinin her aşamasında ağzınızın kalıpları alınır</li><li>Şeffaf düzelticiler yapılır</li><li>Her bir düzeltici yaklaşık iki hafta takılır.</li></ul></p><p>smileizmir Estetik Diş Kliniği Ortodonti birimimizde kliniklerimizin direktörü Prof. Dr.Tancan UYSAL ve ekibi tarafından hastalarımıza en uygun tedavi seçeneği klinik muayene sonrasında hastalarımıza sunulmakta ve hastalarımızın tercihine göre tedavileri yapılmaktadır.</p>"
  },
  "en": {
    "title": "Orthodontics with Transparent Plaques",
    "description": "Orthodontic Treatment with Transparent Plaque; Clear plates are a reliable method of treatment with an approximate history of 20 years.",
    "content1": "<p> Orthodontic Treatment with Transparent Plate; Clear plates are a reliable method of treatment with an approximate history of 20 years. Transparent plaques cannot be noticed when viewed from the outside. Even your closest ones (friends, family) will have a hard time noticing. There is the possibility of plugging and unplugging at any time. It is a painless treatment method. Pain, aches and pains, which are frequently encountered in metal braces, are absolutely not encountered. </p> <p> Transparent plaques do not experience an aesthetic concern like metal or transparent braces. You can continue your family, business and social life without any worry. Especially, it prevents the psychological problems experienced by children and young people in the treatment of tooth distortion. </p> <p> Thanks to the plaque layer covering the teeth, orthodontic interventions are performed in the mouth. Transparent plates can be easily removed and installed, easy to use with its soft structure, and it is a very aesthetic treatment tool with its completely transparent structure. </p>",
    "accord1title": "How to Prepare Transparent Plates?",
    "accord1": "<p>The dentist takes measurements orally. It transfers this information to the computer by three-dimensional scanning method. A treatment plan scenario about the movement of the teeth is obtained on the computer. The treatment route is determined according to these scenarios. The desired tooth molds are made from the three-dimensional printer. A flexible transparent plate is applied on these molds. A plate suitable for each step is prepared for the path to be covered during the treatment stages. Thus, the plates to be used in treatment are prepared.</p>",
    "accord2title": "How to Use Plates?",
    "accord2": "<p>Transparent plaques are placed on the teeth, they cover the teeth and move the teeth in the desired direction as long as they are in the mouth. The use of the plate is in the form of placing it in the mouth, removing it in activities such as eating, drinking, brushing teeth, using dental floss. In other words, the person can remove and put the record himself. He himself uses the record as a part of his daily life.</p>",
    "accord3title": "When Does The Treatment Start After Measuring?",
    "accord3": "<p>Considering the entry of the information into the computer after the measurements are taken and the preparation time of the molds, transparent plates are obtained after about two weeks. In other words, the plates are taken after two weeks and placed in the mouth and the treatment is started.</p>",
    "accord4title": "How Does The Treatment Process Progress With Transparent Plates?",
    "accord4": "<p> Unlike normal orthodontic treatment in transparent plates, brackets are produced by 3D printers specially for the person. As long as the plaques are in the mouth, they direct the teeth towards the desired movement. The plaque is changed every 15 days, and with every change, that is, each new plaque, the teeth are advanced in a planned way. </p> <p> During the treatment, patients can easily follow the plaques themselves, it is quite simple, a plaque is about 20 hours a day. About two weeks after using the plate, the plate of the next step is given to be used. They wear this plate for 20 hours a day for two weeks in the same way. </p>",
    "accord5title": "What is the Treatment Time in Transparent Plate Use?",
    "accord5": "<p>Average treatment time, about 60% of problems end in eight to ten months. The remaining 40% may end with twelve to fourteen months of treatment. There are also rare cases that last a maximum of 16-18 months.</p>",
    "accord6title": "What Are The Advantages Of Using Transparent Plate Over Fixed Brackets?",
    "accord6": "<p> Plaque has many advantages over braces. All the movements made are determined primarily in three-dimensional simulations. After that, the amount of unwanted movement is very low, there is not much risk, there is no finding that it causes less damage to the teeth or more damage to the teeth than braces. </p> <p> They are quite transparent at this point. They have an aesthetic appearance, from the outside, it cannot be understood whether the treatment of the user continues, the treatment or the process of the treatment. </p> <p> Since the patient is produced individually, there is no problem. It does not disrupt social life, someone using transparent plates can easily continue their natural behaviors such as laughing and talking in society. He does not cover his mouth with his hand while speaking. While the picture is taken, he does not laugh so that his wires are not visible, he continues to live easily in the natural flow of life, he is in a treatment process, but the quality of life does not decrease. </p> <p> Since it can be removed in meals, it can be eaten easily, this is one of the biggest advantages compared to strings. The other big advantage is that cleaning is much easier. While it is difficult to clean the food entering the teeth in the wires, the transparent plaques can be removed, so the user can easily clean all their teeth. The biggest advantages of the use of plaque are that it does not affect social life with its aesthetic appearance and that the desired foods can be consumed and dental hygiene can be achieved easily. During the treatment process, when the clinic comes to the clinic, plate changes are made in a short time, since there will be no treatment applications such as wire adjustment, tightening, change as in metal brackets, the time spent in the clinic is considerably less than the wires. p> <p> If the treatment is suitable, a few plates can be given to the patient and the process can be given to him / her, the time to come to the clinic is reduced, the patient can use the plates one after the other if the treatment is appropriate. they apply as much force as necessary to the desired areas. </p>",
    "accord7title": "What are the Disadvantages of Using Transparent Plate?",
    "accord7": "<p> When transparent plate users first put on the plate, there may be a slight increase in their saliva secretion, and a slurred speech can be seen during the adjustment process. </p> <p> We can count it as a disadvantage that it is more costly than fixed brackets. </p>",
    "accord8title": "What are the Differences Between Using Transparent Plaque and Using Braces?",
    "accord8": "<p> There are cases when the wire breaks or comes off in metal brackets. In these cases, you go to the clinic and the dentist places the wire. Clinical visits are essential in such possible scenarios. Transparent plaque user undergoes a more independent treatment process, not dependent on the dentist. He / she should write only control appointments in his / her agenda, as he / she does not have to go to the clinic when he / she is sick or busy, and he / she does not have to have extra clinic visits. The question asked by the patients using metal brackets in almost every examination is when the braces will be removed, whereas in invisalign technology, patients do not worry about the duration of the treatment. </p> <p> Another disadvantage is that the gums can be injured when the braces are broken, stinging or stinging due to metal devices or wires in the mouth. There is a situation of injury, mostly a physician's intervention is required, such situations are not seen in plaques, the situation that needs to be intervened is very rare, it does not disturb the teeth and gums. Compared to the treatment applied with braces, it offers a more comfortable use and a painless treatment process without wounds.It is a more painless and painless process compared to treatment with metal brackets. </p>",
    "accord9title": "Is There An Age Limit For Using Transparent Plaque?",
    "accord9": "<p>It can be used easily in all age groups. There is no age limit for invisalign use. Children, teenagers and adults can use transparent plates. The important thing is to use the plate regularly in cooperation with the physician.</p>",
    "accord10title": "What Should Be Considered When Using Transparent Plate?",
    "accord10": "<p>When using a transparent plate, it should be in cooperation with the physician, and the plate should be used regularly and kept in the mouth. Due to the flexible nature of the plate, excessively hot beverages should not be consumed. The plate can lose its form by stretching due to heat.</p>",
    "accord11title": "Is Smoking Allowed While Using Plaque?",
    "accord11": "<p>Excessive consumption of tea, coffee and cigarettes can cause yellowing of the plaques. However, since the plates are changed after 15 days, no effort is required to correct the color. However, there may be situations where your teeth need to be cleaned in sessions by paying a fee in fixed orthodontic treatment.</p>",
    "accord12title": "Is It Necessary To Have A General Dental Examination Before Invisalign Treatment?",
    "accord12": "<p> Before starting the treatment, a dental examination should be done and the necessary filling process, tartar cleaning, decays should be cleaned, and oral care should be done. Such procedures are not performed after the treatment is started. However, prosthetic procedures such as implants are left after the treatment. </p> <p> Transparent plaque treatment can be applied before the orthognathic surgery operation and the problems in the mouth after the operation are eliminated. </p>",
    "accord13title": "Is Invisalign a More Costly Treatment Than Fixed Brackets?",
    "accord13": "<p> Previously, Invisalign was a more costly treatment method. Only one firm did this job, it was more expensive, today the prices are more affordable, it has an affordable cost. Still, it is more costly than wires, but there is no gap in between. </p> <p> Here, advantage and disadvantage comparison should be included in the cost calculation. Invisalign is a bit more costly but much more aesthetic and much easier to use. </p>",
    "accord14title": "Would You Recommend Transparent Plaques Compared to Braces Treatments?",
    "accord14": "<p> I do my orthodontic treatment interventions with 80% transparent plates, it is demanded from patients and my patients are satisfied, this is my first choice, digital technologies are quickly integrated into dentistry, there is no point in staying away from this, perfect three-dimensional analyzes are made, it is necessary to apply it. and I see it beneficial. </p> <p> As the patients do not compare themselves with wires, we see that the people around them are not aware of the treatment while the Plaque users we observe in our clinic have their treatments. Since the plaque changes every two weeks, there is no odor, no disturbance. </p> <p> They can continue this easy-to-use treatment in an aesthetic and hygienic manner. They are able to remove plaques in very important meetings, they can use their rights to remove them for a few hours a day in special situations. </p> <p> We see that the people who receive orthodontic treatment do not laugh in their pictures and on their social media accounts until the end of their treatment. they can behave comfortably. In this respect, it is a treatment method that does not interrupt social life. According to the records, ten million people around the world have received treatment with transparent plates and the results are very positive. </p> <p> Transparent plates are an easy, aesthetic and healthy method that moves teeth to the ideal position. That's why I generally use transparent plates in my treatment applications. </p>",
    "accord14title": "Advantages of Transparent Plates",
    "accord14": "<p> The time spent in the dentist's chair is less. When you use traditional braces, you have to visit your dentist as often as every two weeks for some adjustments. When you use transparent correctors, you will visit your doctor every six weeks and they will give you another set of corrective plates. </p> <p> Oral hygiene will be better. Unlike traditional braces, you can remove your clear correctors while eating, drinking or brushing your teeth. </p> <h4> Treatment Process </h4> <p> <ul> <li> Computed tomography captures your teeth </li> <li> Movements of your teeth are predicted with computer-aided design software </li> <li> If necessary, your treatment plan is reviewed </li> <li> At every stage of the treatment, molds of your mouth are taken </li> <li> Transparent correctors are made </li> <li > Each corrector is worn for about two weeks. </li> </ul> </p> <p> In our smileizmir Esthetic Dental Clinic Orthodontics unit, Prof. Dr. Tancan UYSAL and his team present the most suitable treatment option to our patients after clinical examination and are treated according to the preference of our patients. </p>"
  },
  "de": {
    "title": "Kieferorthopädie mit transparenten Plaques",
    "description": "Kieferorthopädische Behandlung mit transparenter Plaque; Klare Platten sind eine zuverlässige Behandlungsmethode mit einer Vorgeschichte von ungefähr 20 Jahren.",
    "content1": "<p> Kieferorthopädische Behandlung mit transparenter Platte; Klare Platten sind eine zuverlässige Behandlungsmethode mit einer Vorgeschichte von ungefähr 20 Jahren. Transparente Plaketten sind von außen nicht erkennbar. Selbst Ihre engsten Freunde (Freunde, Familie) werden es schwer haben, es zu bemerken. Es besteht die Möglichkeit, jederzeit ein- und auszustecken. Es ist eine schmerzlose Behandlungsmethode. Schmerzen, die bei Metallklammern häufig auftreten, treten absolut nicht auf. </p> <p> Transparente Plaques haben keine ästhetischen Bedenken wie Metall oder transparente Klammern. Sie können Ihr familiäres, geschäftliches und soziales Leben ohne Sorgen fortsetzen. Insbesondere verhindert es die psychischen Probleme, die Kinder und Jugendliche bei der Behandlung von Zahndeformitäten haben. </p> <p> Dank der Plaque-Schicht, die die Zähne bedeckt, werden kieferorthopädische Eingriffe im Mund durchgeführt. Transparente Platten können leicht entfernt und installiert werden, sind aufgrund ihrer weichen Struktur einfach zu verwenden und mit ihrer vollständig transparenten Struktur ein sehr ästhetisches Behandlungswerkzeug. </p>",
    "accord1title": "Wie bereite ich transparente Platten vor?",
    "accord1": "<p>Der Zahnarzt nimmt mündlich Messungen vor. Diese Informationen werden durch ein dreidimensionales Scanverfahren an den Computer übertragen. Ein Behandlungsplanszenario über die Bewegung der Zähne wird am Computer abgerufen. Der Behandlungsweg wird nach diesen Szenarien bestimmt. Die gewünschten Zahnformen werden aus dem dreidimensionalen Drucker hergestellt. Auf diese Formen wird eine flexible transparente Platte aufgebracht. Für jeden Schritt wird eine Platte vorbereitet, auf der der Weg während der Behandlungsphasen zurückgelegt werden soll. Somit werden die zur Behandlung zu verwendenden Platten hergestellt.</p>",
    "accord2title": "Wie benutzt man Teller?",
    "accord2": "<p>Transparente Plaques werden auf die Zähne gelegt, sie bedecken die Zähne und bewegen die Zähne in die gewünschte Richtung, solange sie sich im Mund befinden. Die Verwendung der Platte besteht darin, sie in den Mund zu legen und sie bei Aktivitäten wie Essen, Trinken, Zähneputzen und Zahnseide zu entfernen. Mit anderen Worten, die Person kann die Aufzeichnung selbst entfernen und ablegen. Er selbst nutzt die Aufzeichnung als Teil seines täglichen Lebens.</p>",
    "accord3title": "Wann beginnt die Behandlung nach der Messung?",
    "accord3": "<p>Unter Berücksichtigung der Eingabe der Informationen in den Computer nach den Messungen und der Vorbereitungszeit der Formen werden nach etwa zwei Wochen transparente Platten erhalten. Mit anderen Worten, die Platten werden nach zwei Wochen entnommen und in den Mund gelegt, und die Behandlung wird begonnen.</p>",
    "accord4title": "Wie verläuft der Behandlungsprozess mit transparenten Platten?",
    "accord4": "<p> Im Gegensatz zur normalen kieferorthopädischen Behandlung in transparenten Platten werden Brackets von 3D-Druckern speziell für die Person hergestellt. Solange sich die Plaques im Mund befinden, richten sie die Zähne auf die gewünschte Bewegung aus. Die Plaque wird alle 15 Tage gewechselt, und bei jeder Änderung, dh bei jeder neuen Plaque, werden die Zähne auf geplante Weise vorgeschoben. </p> <p> Während der Behandlung können die Patienten die Plaques leicht selbst verfolgen. Es ist ganz einfach, eine Plaque dauert etwa 20 Stunden pro Tag. Etwa zwei Wochen nach Verwendung der Platte wird die Platte des nächsten Schritts zur Verwendung gegeben. Sie tragen diese Platte zwei Wochen lang 20 Stunden am Tag auf die gleiche Weise. </p>",
    "accord5title": "Was ist die Behandlungszeit bei transparenter Plattenverwendung?",
    "accord5": "<p>Durchschnittliche Behandlungszeit, etwa 60% der Probleme enden in acht bis zehn Monaten. Die restlichen 40% können mit einer zwölf- bis vierzehnmonatigen Behandlung enden. Es gibt auch seltene Fälle, die maximal 16 bis 18 Monate dauern.</p>",
    "accord6title": "Was sind die Vorteile der Verwendung einer transparenten Platte gegenüber festen Klammern?",
    "accord6": "<p> Plaque hat viele Vorteile gegenüber Zahnspangen. Alle Bewegungen werden hauptsächlich in dreidimensionalen Simulationen bestimmt. Danach ist das Ausmaß unerwünschter Bewegungen sehr gering, es besteht kein großes Risiko, es gibt keine Ergebnisse in den Studien, dass es weniger Schäden an den Zähnen oder mehr Schäden an den Zähnen im Vergleich zu den Zahnspangen verursacht. </p> <p> Sie sind zu diesem Zeitpunkt ziemlich transparent. Sie haben ein ästhetisches Erscheinungsbild, von außen kann nicht verstanden werden, ob die Behandlung des Benutzers fortgesetzt wird, die Behandlung oder der Prozess der Behandlung. </p> <p> Da der Patient individuell hergestellt wird, gibt es kein Problem. Es stört das soziale Leben nicht, jemand, der transparente Platten verwendet, kann sein natürliches Verhalten wie Lachen und Reden in der Gesellschaft leicht fortsetzen. Er bedeckt seinen Mund beim Sprechen nicht mit der Hand. Während das Bild aufgenommen wird, lacht er nicht, so dass seine Fäden nicht sichtbar sind, er lebt weiterhin leicht im natürlichen Fluss des Lebens, er befindet sich in einem Behandlungsprozess, aber die Lebensqualität nimmt nicht ab. </p> <p> Da es in Mahlzeiten entfernt werden kann, kann es leicht gegessen werden, dies ist einer der größten Vorteile im Vergleich zu Fäden. Der andere große Vorteil ist, dass die Reinigung viel einfacher ist. Während es schwierig ist, die in die Zähne in den Drähten eindringenden Lebensmittel zu reinigen, können die transparenten Plaques entfernt werden, so dass der Benutzer problemlos alle Zähne reinigen kann. Die größten Vorteile der Verwendung von Plaque bestehen darin, dass sie das soziale Leben mit ihrem ästhetischen Erscheinungsbild nicht beeinträchtigt und dass die gewünschten Lebensmittel konsumiert werden können und die Zahnhygiene leicht erreicht werden kann. Während des Behandlungsprozesses, wenn die Klinik in die Klinik kommt, werden Plattenwechsel in kurzer Zeit vorgenommen, da es keine Behandlungsanwendungen wie Drahtanpassung, Anziehen, Ändern wie bei Metallklammern gibt, ist die in der Klinik verbrachte Zeit erheblich kürzer als die Drähte. p> <p> Wenn die Behandlung geeignet ist, können dem Patienten einige Platten gegeben werden und der Prozess kann ihm gegeben werden, die Zeit, um in die Klinik zu kommen, wird verkürzt, der Patient kann die Platten nacheinander verwenden, wenn die Behandlung angemessen ist. Sie üben so viel Kraft wie nötig auf die gewünschten Bereiche aus. </p>",
    "accord7title": "Was sind die Nachteile der Verwendung einer transparenten Platte?",
    "accord7": "<p> Wenn Benutzer einer transparenten Platte die Platte zum ersten Mal aufsetzen, kann es zu einer leichten Zunahme ihrer Speichelsekretion kommen, und während des Anpassungsprozesses ist eine verschwommene Sprache zu sehen. </p> <p> Wir können dies als Nachteil betrachten, dass dies teurer ist als feste Klammern. </p>",
    "accord8title": "Was sind die Unterschiede zwischen der Verwendung von transparenter Plakette und der Verwendung von Zahnspangen?",
    "accord8": "<p> Es gibt Fälle, in denen der Draht bricht oder sich in Metallklammern löst. In diesen Fällen gehen Sie in die Klinik und der Zahnarzt platziert den Draht. In solchen möglichen Szenarien sind Klinikbesuche unerlässlich. Der transparente Plaque-Benutzer durchläuft einen unabhängigeren Behandlungsprozess, der nicht vom Zahnarzt abhängig ist. Er / sie sollte nur Kontrolltermine in seine / ihre Agenda aufnehmen, da er / sie nicht in die Klinik gehen muss, wenn er / sie krank oder beschäftigt ist, und er / sie keine zusätzlichen Klinikbesuche haben muss. Die Frage, die von den Patienten gestellt wird, die bei fast jeder Untersuchung Metallklammern verwenden, ist, wann die Zahnspangen herauskommen, während sich die Patienten bei der Invisalign-Technologie keine Gedanken über die Dauer der Behandlung machen. </p> <p> Ein weiterer Nachteil besteht darin, dass das Zahnfleisch durch Metallvorrichtungen oder Drähte im Mund verletzt, gestochen oder gestochen werden kann. Es gibt eine Narbensituation, meistens ist ein Eingreifen eines Arztes erforderlich, solche Situationen treten bei Plaques nicht auf, die Situation, in die eingegriffen werden muss, ist sehr selten, sie stört Zähne und Zahnfleisch nicht. Im Vergleich zur Behandlung mit Zahnspangen bietet es eine komfortablere Anwendung und einen schmerzfreien Behandlungsprozess ohne Wunden.</p>",
    "accord9title": "Gibt es eine Altersgrenze für die Verwendung von transparenter Plakette?",
    "accord9": "<p>Es kann leicht in allen Altersgruppen verwendet werden. Es gibt keine Altersgrenze für die Invisalign-Verwendung. Kinder, Jugendliche und Erwachsene können transparente Platten verwenden. Wichtig ist, dass Sie die Platte regelmäßig in Zusammenarbeit mit dem Arzt verwenden.</p>",
    "accord10title": "Was ist bei der Verwendung einer transparenten Platte zu beachten?",
    "accord10": "<p>Wenn Sie eine transparente Platte verwenden, sollte diese in Zusammenarbeit mit dem Arzt durchgeführt werden. Die Platte sollte regelmäßig verwendet und im Mund aufbewahrt werden. Aufgrund der Flexibilität der Platte sollten keine übermäßig heißen Getränke konsumiert werden. Die Platte kann durch Dehnen aufgrund von Hitze ihre Form verlieren.</p>",
    "accord11title": "Ist das Rauchen während der Verwendung von Plaque erlaubt?",
    "accord11": "<p>Übermäßiger Konsum von Tee, Kaffee und Zigaretten kann zu einer Gelbfärbung der Plaques führen. Da die Platten jedoch nach 15 Tagen gewechselt werden, ist kein Aufwand erforderlich, um die Farbe zu korrigieren. Es kann jedoch Situationen geben, in denen Ihre Zähne in Sitzungen gereinigt werden müssen, indem eine Gebühr für eine festsitzende kieferorthopädische Behandlung entrichtet wird.</p>",
    "accord12title": "Ist vor einer Invisalign-Behandlung eine allgemeine zahnärztliche Untersuchung erforderlich?",
    "accord12": "<p> Vor Beginn der Behandlung sollte eine zahnärztliche Untersuchung durchgeführt und der erforderliche Füllprozess, Zahnsteinreinigung, Zerfall und Mundpflege durchgeführt werden. Solche Verfahren werden nach Beginn der Behandlung nicht durchgeführt. Prothetische Eingriffe wie Implantate bleiben jedoch nach der Behandlung erhalten. </p> <p> Eine transparente Plaque-Behandlung kann angewendet werden, bevor eine orthognathische Operation durchgeführt und postoperative Probleme im Mund beseitigt werden.</p>",
    "accord13title": "Ist Invisalign eine teurere Behandlung als feste Klammern?",
    "accord13": "<p> Bisher war Invisalign eine teurere Behandlungsmethode. Nur eine Firma hat diesen Job gemacht, es war teurer, heute sind die Preise günstiger, es hat erschwingliche Kosten. Es ist zwar teurer als Drähte, aber es gibt keine Lücke dazwischen. </p> <p> Hier sollte der Vergleich von Vor- und Nachteilen in die Kostenberechnung einbezogen werden. Invisalign ist etwas teurer, aber viel ästhetischer und einfacher zu bedienen. </p>",
    "accord14title": "Würden Sie transparente Plaques im Vergleich zu Zahnspangenbehandlungen empfehlen?",
    "accord14": "<p> Ich mache meine kieferorthopädischen Eingriffe mit 80% transparenten Platten, es wird von den Patienten verlangt und meine Patienten sind zufrieden. Dies ist meine erste Wahl. Digitale Technologien werden schnell in die Zahnmedizin integriert. Es macht keinen Sinn, sich davon fernzuhalten. Es werden perfekte dreidimensionale Analysen durchgeführt. Es ist notwendig, sie anzuwenden. und ich sehe es als vorteilhaft an. </p> <p> Da sich die Patienten nicht mit Drähten vergleichen, sehen wir, dass die Menschen um sie herum sich der Behandlung nicht bewusst sind, während die Plaque-Benutzer, die wir in unserer Klinik beobachten, ihre Behandlungen haben. Da sich die Plaque alle zwei Wochen ändert, gibt es keinen Geruch, keine Störung. </p> <p> Sie können diese benutzerfreundliche Behandlung auf ästhetische und hygienische Weise fortsetzen. Sie können Plaques in sehr wichtigen Besprechungen entfernen und ihre Rechte nutzen, um sie in besonderen Situationen für einige Stunden am Tag zu entfernen. </p> <p> Wir sehen, dass die Personen, die eine kieferorthopädische Behandlung erhalten, bis zum Ende ihrer Behandlung nicht in ihren Bildern und auf ihren Social-Media-Konten lachen. Sie können sich bequem verhalten. In dieser Hinsicht ist es eine Behandlungsmethode, die das soziale Leben nicht unterbricht. Laut den Aufzeichnungen wurden weltweit zehn Millionen Menschen mit transparenten Platten behandelt, und die Ergebnisse sind sehr positiv. </p> <p> Transparente Platten sind eine einfache, ästhetische und gesunde Methode, mit der Zähne in die ideale Position gebracht werden. Deshalb verwende ich in meinen Behandlungsanwendungen im Allgemeinen transparente Platten. </p>",
    "accord14title": "Vorteile von transparenten Platten",
    "accord14": "<p> Die Zeit auf dem Zahnarztstuhl ist geringer. Wenn Sie herkömmliche Zahnspangen verwenden, müssen Sie Ihren Zahnarzt alle zwei Wochen aufsuchen, um einige Anpassungen vorzunehmen. Wenn Sie transparente Korrektoren verwenden, werden Sie alle sechs Wochen Ihren Arzt aufsuchen und Ihnen einen weiteren Satz Korrekturplatten geben. </p> <p> Die Mundhygiene ist besser. Im Gegensatz zu herkömmlichen Zahnspangen können Sie Ihre klaren Korrektoren beim Essen, Trinken oder Zähneputzen entfernen. </p> <h4> Behandlungsprozess </ h4> <p> <ul> <li> Die Computertomographie erfasst Ihre Zähne </li> <li> Bewegungen Ihrer Zähne werden mit einer computergestützten Konstruktionssoftware vorhergesagt. </li> <li> Falls erforderlich, wird Ihr Behandlungsplan überprüft. </li> <li> In jedem Stadium der Behandlung werden Mundformen entnommen. </li> <li> Es werden transparente Korrektoren hergestellt. </li> <li > Jeder Korrektor wird ungefähr zwei Wochen lang getragen. </li> </ ul> </p> <p> In unserer Abteilung für kieferorthopädische Zahnklinik smileizmir Esthetic hat Prof. Dr. Tancan UYSAL und sein Team stellen unseren Patienten nach der klinischen Untersuchung die am besten geeignete Behandlungsoption vor und werden gemäß den Präferenzen unserer Patienten behandelt. </p>"
  }
}
</i18n>
<template>
  <div>
    <SocialHead :title="$t('title')" :description="$t('description')" />
    <Subheader :baslik="$t('title')" />
    <section class="services whitepage">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <div class="row">
              <div class="col-md-12 onStep">
                <img alt="imgservices" class="img-responsive" src="/image/tedaviler/seffaf-plaklarla-ortodontik-tedaviler.webp">
                <h2 v-html="$t('title')"></h2>
              </div>
              <div class="col-md-12" v-html="$t('content1')"></div>
              <div class="col-md-12">
                <AccordionLayout>
                  <Accordion :title="$t('accord1title')" :content="$t('accord1')" />
                  <Accordion :title="$t('accord2title')" :content="$t('accord2')" />
                  <Accordion :title="$t('accord3title')" :content="$t('accord3')" />
                  <Accordion :title="$t('accord4title')" :content="$t('accord4')" />
                  <Accordion :title="$t('accord5title')" :content="$t('accord5')" />
                  <Accordion :title="$t('accord6title')" :content="$t('accord6')" />
                  <Accordion :title="$t('accord7title')" :content="$t('accord7')" />
                  <Accordion :title="$t('accord8title')" :content="$t('accord8')" />
                  <Accordion :title="$t('accord9title')" :content="$t('accord9')" />
                  <Accordion :title="$t('accord10title')" :content="$t('accord10')" />
                  <Accordion :title="$t('accord11title')" :content="$t('accord11')" />
                  <Accordion :title="$t('accord12title')" :content="$t('accord12')" />
                  <Accordion :title="$t('accord13title')" :content="$t('accord13')" />
                  <Accordion :title="$t('accord14title')" :content="$t('accord14')" />
                </AccordionLayout>
             </div>
            </div>
          </div>
          <div class="col-md-3 onStep">
              <Tedavilerrightwidget />
        </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import SocialHead from '@/components/SocialHead'
import Subheader from '@/components/subheader'
import Accordion from '@/components/tekrarlayan/accordion'
import AccordionLayout from '@/components/tekrarlayan/accorlayout'
import Tedavilerrightwidget from '@/components/tedavilerrightwidget'

export default {
  name: 'seffaf-plaklarla-ortodonti',
  layout: "page",
  components: {
    SocialHead,
    Subheader,
    Accordion,
    AccordionLayout,
    Tedavilerrightwidget
  },
  nuxtI18n: {
    seo: true,
    paths: {
      tr: '/seffaf-plaklarla-ortodonti',
      en: '/orthodontics-with-transparent-plaques',
      de: '/kieferorthopadie-mit-transparenten-plaques'
    }
  },
  mounted() {
    this.$nextTick(() => {
      this.$nuxt.$loading.start()
      setTimeout(() => this.$nuxt.$loading.finish(), 500)
    })
  }
}
</script>

<style scoped>

</style>
